[package]
name = "rp-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.14.1"

[[bin]]
name = "rp_main"
path = "src/bin/main.rs"
